services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    # map to a different host port to avoid collisions with local Postgres
    ports:
      - 5433:5432

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/chatapp

volumes:
  pgdata:
