[pytest]
minversion = 7.0
addopts = --strict-markers -q
testpaths = tests
filterwarnings =
    ignore:The garbage collector is trying to clean up:sqlalchemy.exc.SAWarning

[coverage:run]
branch = True
source = project
